# Generated by Django 4.2.5 on 2023-09-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='content',
            field=models.TextField(default='Default Content'),
        ),
    ]
